'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = Object.freeze({
  PROD: true,
  DEFAULT_SYMBOL: 'BTCBRL',
  DEFAULT_CURRENCY: 'BRL',
  BTC_CURRENCY: 'BTC',
  DEFAULT_TICK: 'BLINK:BTCBRL',
  BROKER_ID: 4,
  ORDER_MIN_PRICE: 10000,
  HEARTH_BEAT_TIME: 25000,

  ORDERBOOK: {
    NEW_ORDER: 'OB:NEW_ORDER',
    UPDATE_ORDER: 'OB:UPDATE_ORDER',
    DELETE_ORDER: 'OB:DELETE_ORDER',
    DELETE_ORDER_THU: 'OB:DELETE_ORDERS_THRU',
    TRADE_NEW: 'OB:TRADE_NEW'
  },

  EXECUTION_REPORT: {
    NEW_EXECUTION: 'EXECUTION_REPORT:NEW',
    PARTIAL_EXECUTION: 'EXECUTION_REPORT:PARTIAL',
    COMPLETE_EXECUTION: 'EXECUTION_REPORT:EXECUTION',
    CANCELED_EXECUTION: 'EXECUTION_REPORT:CANCELED',
    REJECTED_EXECUTION: 'EXECUTION_REPORT:REJECTED'
  }
});